BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Notes" (
	"NoteId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"NoteText"	TEXT NOT NULL,
	"NoteTypeId"	INTEGER NOT NULL,
	"SpiritId"	INTEGER NOT NULL,
	FOREIGN KEY("SpiritId") REFERENCES "Spirit"("SpiritId"),
	FOREIGN KEY("NoteTypeId") REFERENCES "NoteType"("NoteTypeId")
);
CREATE TABLE IF NOT EXISTS "NoteType" (
	"NoteTypeId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"NoteTypeText"	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "Spirit" (
	"SpiritId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"DistilleryId"	INTEGER NOT NULL,
	"Expression"	TEXT NOT NULL,
	"CountryId"	INTEGER NOT NULL,
	"ABV"	INTEGER NOT NULL CHECK(ABV>=0 and ABV<=100),
	"Score"	INTEGER NOT NULL CHECK(Score>=0 and Score<=100),
	"SpiritTypeId"	INTEGER NOT NULL,
	FOREIGN KEY("DistilleryId") REFERENCES "Distillery"("DistilleryId"),
	FOREIGN KEY("CountryId") REFERENCES "Country"("CountryId"),
	FOREIGN KEY("SpiritTypeId") REFERENCES "SpiritType"("TypeID")
);
CREATE TABLE IF NOT EXISTS "SpiritVariant" (
	"VariantId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"VariantName"	INTEGER NOT NULL UNIQUE,
	"SpiritTypeId"	INTEGER NOT NULL,
	FOREIGN KEY("SpiritTypeId") REFERENCES "SpiritType"("TypeID")
);
CREATE TABLE IF NOT EXISTS "SpiritType" (
	"TypeID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"TypeName"	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "Country" (
	"CountryId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"CountryName"	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "Distillery" (
	"DistilleryId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"DistilleryName"	TEXT NOT NULL UNIQUE
);
COMMIT;
